#importonce

// Requires generated_model_header.asm (OUTPUT_CLASSES) to be imported first.
.const USE_PAIRED_POPCOUNT=1
#define USE_PAIRED_POPCOUNT
.const ENABLE_INFERENCE_ABORT=1

.const TTA_AUTO=0
.const TTA_EARLY_ONLY=1
.const TTA_FULL=2
.const TTA_FULL2X=3
.const TTA_DEFAULT_MODE=TTA_AUTO

.const INCLUDE_VERIFICATION_SCORES=0

.const IMAGE_SIDE=24
.const C1_PLANE_ROW_BYTES=IMAGE_SIDE >> 3
.const C1_SOURCE_ROW_STEP=2*C1_PLANE_ROW_BYTES
.const PLANE_BYTES=IMAGE_SIDE*C1_PLANE_ROW_BYTES
.const SCORE_BYTES=2*OUTPUT_CLASSES
